"""Mandatory disclaimer shown on every generated report."""

from __future__ import annotations

DISCLAIMER: str = (
    "DISCLAIMER: This report is generated by an automated AI system and is "
    "provided for informational and research purposes only. It does not "
    "constitute financial, investment, legal, or tax advice. Neither this "
    "tool nor its author assumes any responsibility or liability for any "
    "action taken based on this report. You retain full and sole "
    "responsibility for any investment decision you make."
)
